[tool.poetry]
name = "poetry-instance"
version = "1.7.1"
description = ""
authors = []
license = ""

[tool.poetry.dependencies]
poetry = "1.7.1"
python = "^3.8"

[tool.poetry.group.additional.dependencies]
poetry-templating = { path = "..", develop = true }
